### ISSUE TITLE
Issue with running a second environment of SGD

### ISSUE THREAD

**Issue by traeuker** [automl/DACBench#95]
I get errors running a evaluation environment with SGD. The training environment works fine.

Error Message is: 
```
Traceback (most recent call last):
  File "/home/raeuker/ms/TempoDAC/run.py", line 160, in <module>
    max_train_time_steps=args.training_steps)
  File "/home/raeuker/ms/TempoDAC/core/dqn.py", line 124, in train
    eval_s, eval_r, eval_d = self.eval(eval_eps, max_env_time_steps)
  File "/home/raeuker/ms/TempoDAC/core/dqn.py", line 211, in eval
    s = self._eval_env.reset()
  File "/home/raeuker/ms/DACBench/dacbench/envs/sgd.py", line 291, in reset
    self.get_default_reward(self)
  File "/home/raeuker/ms/DACBench/dacbench/envs/sgd.py", line 387, in get_default_reward
    reward = self._train_batch_()
  File "/home/raeuker/ms/DACBench/dacbench/envs/sgd.py", line 375, in _train_batch_
    loss.mean().backward()
  File "/home/raeuker/env/lib64/python3.6/site-packages/torch/tensor.py", line 221, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/raeuker/env/lib64/python3.6/site-packages/torch/autograd/__init__.py", line 132, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```
For some reason `loss.mean()` is missing `grad_fn=<MeanBackward0>`.

**Comment by traeuker** [comment]
The issue dose not resolve for me in sgd_dev btw.

**Comment by TheEimer** [comment]
@Steven-Adriaensen, do you know what's happening here?

**Comment by traeuker** [comment]
I think I know now, why this is happening. Unfortunately its because of my lack of experience in pytorch: 
I tried evaluating within my second environment with "with torch.no_grad()". This applies for all graphs within this expression and also for the graphs within the SGD benchmark, if it is implemented in pytorch.
It works without torch.no_grad()!
