### ISSUE TITLE
Random socket.timeouts in FD environments 

### ISSUE THREAD

**Issue by traeuker** [automl/DACBench#96]
During longer runs of FD I sometimes get this error message.
This also often happens when I run FD with slurm, could be a completely unrelated issue, though. 
```
Traceback (most recent call last):
  File "/home/raeuker/ms/DACBench/dacbench/envs/fast_downward.py", line 387, in reset
    self.conn, address = self.socket.accept()
  File "/usr/lib64/python3.6/socket.py", line 205, in accept
    fd, addr = self._accept()
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/raeuker/ms/TempoDAC/run.py", line 160, in <module>
    max_train_time_steps=args.training_steps)
  File "/home/raeuker/ms/TempoDAC/core/dqn.py", line 107, in train
    s = self._env.reset()
  File "/home/raeuker/ms/DACBench/dacbench/envs/fast_downward.py", line 390, in reset
    "Fast downward subprocess not reachable (time out). "
OSError: Fast downward subprocess not reachable (time out). Did you run './dacbench/envs/rl-plan/fast-downward/build.py' in order to build the fd backend?
```

**Comment by maximilianreimer** [comment]
Hi, 
thank for the bug report. Could you please change the config value `fd_logs` of FD  to `path/of/your/choice`, run your code again and provide the content of the `dferr.txt` and  `fdout.txt` in the `path/of/your/choice` folder? 

I suspect your `fderr.txt`is going to look similar to this one:
```
OpenBLAS blas_thread_init: pthread_create failed for thread 1 of 4: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 63696 current, 63696 max
OpenBLAS blas_thread_init: pthread_create failed for thread 2 of 4: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 63696 current, 63696 max
OpenBLAS blas_thread_init: pthread_create failed for thread 3 of 4: Resource temporarily unavailable
OpenBLAS blas_thread_init: RLIMIT_NPROC 63696 current, 63696 max
```

If that's the case I am currently investigating this issue and a hotfix for it is to set the environment variable OPENBLAS_NUM_THREADS=1. (More details [here](https://stackoverflow.com/questions/52026652/openblas-blas-thread-init-pthread-create-resource-temporarily-unavailable))

Could you please tell me if that works for you too? 

Cheers
